{% set name = "markdown-it-py" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3ef7346879c931684500cf2ec35c2545b617dd49e8ce3ea4287bb66405913c1a

build:
  number: 0
  entry_points:
    - markdown-it = markdown_it.cli.parse:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attrs >=19.3,<21
    - mdit-py-plugins >=0.2.1,<0.3.0
    - python >=3.6

test:
  imports:
    - markdown_it
    - markdown_it.cli
    - markdown_it.common
    - markdown_it.extensions
    - markdown_it.extensions.container
    - markdown_it.extensions.deflist
    - markdown_it.extensions.dollarmath
    - markdown_it.extensions.footnote
    - markdown_it.extensions.front_matter
    - markdown_it.extensions.myst_blocks
    - markdown_it.extensions.myst_role
    - markdown_it.extensions.texmath
    - markdown_it.helpers
    - markdown_it.presets
    - markdown_it.rules_block
    - markdown_it.rules_core
    - markdown_it.rules_inline
  commands:
    - markdown-it --help

about:
  home: https://github.com/ExecutableBookProject/markdown-it-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python port of markdown-it. Markdown parsing, done right!
  doc_url: https://github.com/ExecutableBookProject/markdown-it-py/blob/master/README.md
  dev_url: https://github.com/ExecutableBookProject/markdown-it-py

extra:
  recipe-maintainers:
    - chrisjsewell
