{% set name = "markdown-it-py" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36be6bb3ad987bfdb839f5ba78ddf094552ca38ccbd784ae4f74a4e1419fc6e3

build:
  number: 0
  entry_points:
    - markdown-it = markdown_it.cli.parse:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attrs >=19.3,<22
    - python >=3.6
    - typing_extensions >=3.7.4

test:
  requires:
    - pip
  imports:
    - markdown_it
    - markdown_it.cli
    - markdown_it.common
    - markdown_it.helpers
    - markdown_it.presets
    - markdown_it.rules_block
    - markdown_it.rules_core
    - markdown_it.rules_inline
  commands:
    - markdown-it --help
    - pip check

about:
  home: https://github.com/ExecutableBookProject/markdown-it-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python port of markdown-it. Markdown parsing, done right!
  doc_url: https://github.com/ExecutableBookProject/markdown-it-py/blob/master/README.md
  dev_url: https://github.com/ExecutableBookProject/markdown-it-py

extra:
  recipe-maintainers:
    - dopplershift
    - choldgraf
